### ISSUE TITLE
Player passwords need to be encrypted

### ISSUE THREAD

**Issue by zelerin** [mutgos/mutgos_server#13]
Currently, Player passwords are unencrypted and stored in the database plaintext.  This needs to be fixed, preferably without adding new dependencies (using common system dependencies is fine).

**Comment by hyena** [comment]
`bcrypt` is my usual goto for this.

The openbsd implementation is simple enough that I could probably take a pass at including it in the code base directly. (https://github.com/openbsd/src/blob/master/lib/libc/crypt/bcrypt.c)

**Comment by zelerin** [comment]
Not pulling in another dependency is definitely a plus.  If you'd like to give this a try, feel free (and let me know so I can assign it)!  Once you've determined you can indeed import the code, just reply with a quick overview of where you plan to put the code and where it will integrate in MUTGOS, or if you need help figuring that out let me know too.

**Comment by hyena** [comment]
I'll get on this after SSL.

**Comment by zelerin** [comment]
This has been fixed by #33
