### ISSUE TITLE
Socket SSL support needs to be added

### ISSUE THREAD

**Issue by zelerin** [mutgos/mutgos_server#14]
Currently, the socket driver supports plaintext (unencrypted) only.  SSL support needs to be added.  The classes were designed knowing this would eventually happen, so it should be relatively easy to integrate it using BOOST.

**Comment by zelerin** [comment]
I suggest opening a second port for encrypted connections, to leave plaintext as an option.  It should all be doable within the socket driver.

**Comment by hyena** [comment]
Yes, I'm planning to take an approach where both a plaintext and SSL port can be opened, similar to FB's commandline options.

**Comment by zelerin** [comment]
Sounds good.  This will tie into #5 at some point.  Eventually I was thinking individual sites could have their own dedicated port (if desired) like a traditional MU*, but that's lower priority for now.

**Comment by hyena** [comment]
Approaching the implementation of this via a subclass of PlainRawSocketConnection (`SecureRawSocketConnection`) and I have a question: What's the consequence of `RawSocketConnection::start()` blocking? What about it making an async call that never returns?

**Comment by hyena** [comment]
```
% Trying to connect to (unnamed1): 127.0.0.1 7072.
% Connected to (unnamed1) using cipher ECDHE_RSA_AES_256_GCM_SHA384.
Welcome to the MUTGOS Alpha Demo.
Pick a site below and connect to it like this: connect <site#> myplayer mypassword
example: connect 2 oren specialword

SITE #     NAME                   DESCRIPTION
---------------------------------------------
   1      <Not implemented>
   2      <Not implemented>


_________(unnamed1)____________________________________________________________________________________________________________________________________________________________________________________________20:34


```

Still got some bugs to work out but it's a start.

**Comment by hyena** [comment]
Questions for this approach:
  - Should the user be able to disable it if they don't want to deal with OpenSSL? For now, I lean towards no and we can make it optional if necessary.
  - Should we have a separate SocketConnectionListener for the SSL port? I think so.

**Comment by zelerin** [comment]
If you find enough code reuse in PlainRawSocketConnection, by all means subclass it.  If there's no real code reuse, just make a new class and inherit from RawSocketConnection directly.  I highly doubt there will be a third socket type, so either implementation should be fine.  start() should never block; you should consider all methods in socketcomm to be nonblocking at this time.  There is a single thread for all socket and websocket I/O, and if it's blocked then no one else can get anything.

At some point, when we start resolving hostnames, we may need a nonblocking resolver task (maybe as a new driver just to fit into the existing paradigm if ASIO doesn't have a way to do it built-in), but for now everything should be nonblocking; methods do whatever work is tasked or due and then return immediately.

For the first question, there will need to be a way to disable SSL sockets at some point.  I'm OK if you want me to do it when I make the config file, but it needs to be set up in such a way that it's easy to add the if check.  Additionally, I'd suggest either checking in instructions or a shell script that explain how to make a self signed certificate easily.  Certificates can be tricky and I wouldn't want someone blocked because they don't understand how to make one just to get the server started locally.  FuzzBall has a script like that, in fact.

For the second question, a quick look at the code suggests a separate ConnectionListener for SSL is needed.  I suspect subclassing and/or refactoring would reduce how much new code must be written, and then you just plug it into the SocketDriver.  On the plus side, I can then easily turn off the encrypted port in the Driver (if specified in the config file) with very little effort later.

Good work so far!

**Comment by hyena** [comment]
* I'm going to stick with subclassing for now, based on the Liskov Substitution Principle. It seems like the most intuitive way.
 * Regarding disabling: Users will definitely not need to enable SSL at runtime. Nor will they be required to create a `server.pem`. An identity.pem has been included with these changes that can be used for local testing. For the time being, SSL will always be on and always enabled on port 7073. When the config file or commandline options are further along, it'll be configurable from there. Whether one is open by default or not is a UX decision. What I'm really asking though is whether we need to support disabling it at COMPILE time. For the time being, I think we won't. It means I'll have to add OpenSSL to the dependency list. 
 * I will make an issue to write up instructions for creating a self-signed .pem with `openssl` as well as one for `certbot`.
 * As for the SocketDriver and Connect Listeners, the Driver will need to have two ConnectionListeners. That means its `start()` logic will be slightly more complicated but not too bad. I've thought about how to refactor ConnectionListener to support either Plain or Secure connections and I think the cleanest way is to make its constructor take in a factory function that creates ConnectionPointers of the appropriate type. If I can accomplish that in away that doesn't look too arcane to me, you can judge it in code review.

**Comment by hyena** [comment]
Style question: What's the clean approach in the codebase for this situation:
```
        // TODO(hyena): Support password callbacks for the certificate?
        ssl_context.use_certificate_chain_file("server.pem");
        ssl_context.use_private_key_file("server.pem", boost::asio::ssl::context::pem);
```

These calls will fail if the `"server.pem"` file is missing or invalid. As written, these will throw a `boost::system::system_error`. If the system is configured to use ssl and the certificate is missing, this should be fatal. Should we:
 1. Let the exception kill the process? (probably not since this will core dump)
 2. Catch the exception and LOG(fatal)?
 3. Use the boost functions that manipulate a `boost::system::error_code` instead?

**Comment by nyanster** [comment]
> FuzzBall has a script like that, in fact.

Fuzzball had a Makefile target to make a self-signed certificate, but it was removed sometime in 2018.

**Comment by zelerin** [comment]
@hyena, I went ahead and approved the merge, even though I saw the same issues with error handling.  Since we're not even close to a v1.0, there is lots of time to add error handling, etc, especially after I get the config file implemented.  I fully expect we'll be going through this and other areas eventually and add better error handling.  The rest of the implementation looked fine to me. There are always multiple approaches to solving a problem, and I think yours was fine.

Right now if MUTGOS encounters a fatal error (files not found, can't open ports, etc), it just logs the error(s), returns failure from the start() method, and lets the main method detect the failure and shut down nicely.  Remember, other components that are started (especially database) may need to cleanly shut down - exiting hard within your subsystem would prevent that.

From what I see in my main method, it detects the error but doesn't quit immediately, which means other components may coredump.  Something to fix later... :)

**Comment by zelerin** [comment]
Forgot to add: For compile time, I'm not too worried about disabling features yet.  This is mostly because stuff like openSSL is extremely common on basically every system.  The 'bang for the buck' to work on that right now is minimal.  You've made the code easy to work on later if this is needed.

**Comment by hyena** [comment]
#31 filed for going back to improve error handling of `server.pem` so we don't lose track of it.

Regarding disabling features, I would prefer to not support compiling Mutgos without SSL support in 2019.
