### ISSUE TITLE
How to store external software dependencies?

### ISSUE THREAD

**Issue by zelerin** [mutgos/mutgos_server#28]
Some of our dependencies (AngelScript, etc) are hosted on smaller web sites; constantly downloading them from the source is not fair for the owner's bandwidth.  Also, should an older version be harder to download or disappear, we want to continue building with it anyway.

How should these dependencies be stored here?  A new repo/project?  Integrated into this project?  I honestly don't know how to handle this yet; suggestions are welcome.

**Comment by hyena** [comment]
Hm. Do we know what their limited bandwidth is? A 1.9M zip file means 500 downloads will be 1 GB of upload. `traceroute` suggests they're hosted on justhost.com and as far as I can see that service lacks a quantitative limit on bandwidth.

Boost I'm sure is fine and rapidjson we can download from github on Microsoft's nickel. So if it's AngelScript is a concern the easiest option is probably to include their code in our codebase. Looks like it has a zlib license which means this should be legal as long as we include the appropriate license file and author file in the subdirectory. This would also mean we could build and embed AngelScript in mutgos so the user has one less system dependency to download/install.

**Comment by zelerin** [comment]
Good points.  I'll go ahead and close this issue and worry about what needs to be embedded in our build when we near v1.0.  It is likely rapidjson and AngelScript will be embedded since they are small and we will be tied to very specific versions.  As far as I can tell, Boost doesn't make major API changes between revisions, so it should be safe to leave it as an external dependency.
