### ISSUE TITLE
ssl support in dockerfile

### ISSUE THREAD

**Issue by hyena** [mutgos/mutgos_server#32]
The Dockerfile should generate a .pem file contianing a self-signed key and a certificate.

**Comment by zelerin** [comment]
This could be used to integrate the configfile stuff into Docker, since it's all related.

**Comment by hyena** [comment]
Assign this to me now. I'll copy in the configfile too.

**Comment by zelerin** [comment]
Assigned.  As I said in email, if you need any changes to how the configfile works, it can certainly be done.  You might be able to take advantage of its ability to use relative paths to make it easier... if so, it might just require some slight changes to the .conf file that's checked in so it works by default.. or just sed it a few times.
