### ISSUE TITLE
String and Document size limits

### ISSUE THREAD

**Issue by zelerin** [mutgos/mutgos_server#7]
Related to #6, global limits on string and Document property sizes should be established, with a policy on how to deal with strings that exceed the length specified and implemented.  I don't currently have a preference for the best way to do this.  Should it be in dbtypes?  In the primitives?  Somewhere else?

**Comment by zelerin** [comment]
Let's start discussion on this.  From what I remember, MUCKs (and likely other text games) tend to simply cut off the ends of long lines rather than reject the entire thing.  Is this the approach we want to take, or would it be better to reject the whole thing and give an error?  The primary reason for the size limits are to prevent malicious (and accidental) attempts to use all the memory.

There are a only a few areas in the code where this could happen:
  * comminterface of course, where user input flows through.
  * dbtypes, where all the database Entity types are.  There are many fields of type string, and there is Document which is basically a list of strings.
  * Optionally, ExternalText could check for sanity.

AngelScripts don't really have an issue because they have a limited heap size.

General string, Document, and username sizes are probably best set as a global in the config file, since it impacts all sites and is not something you'd want to just casually change.  It will be trivial (though tedious) to add size checks at the appropriate parts and would not take too long, but the question first is how it should behave: reject or chop off?  Thoughts?

**Comment by nyanster** [comment]
Rejection would help people not accidentally do buffer-breaking poses. :P  It's something I see some people accidentally do, on Tapestries.  Write a pose so long, the end gets cut off but it still gets sent.  If they notice, they simply spoof the second part of their pose, but if they don't notice, someone has to poke them.
I'm myself am fine with either way here, but that is an anecdote to think about.

**Comment by zelerin** [comment]
That's the exact situation I was thinking of (long poses or even descriptions), in fact!  Descriptions are even worse because they may never realize it was rejected, and years later someone will go through a room and wonder how the description was supposed to end.  I'll be curious to see what @hyena thinks.

**Comment by zelerin** [comment]
Making good progress on this.  The code is done; am currently reviewing it and then will test.
